# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.23

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.23.2/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.23.2/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/justas/stutter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/justas/stutter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.21.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.23.2/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justas/stutter/CMakeFiles /Users/justas/stutter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/justas/stutter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named stutter

# Build rule for target.
stutter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 stutter
.PHONY : stutter

# fast build rule for target.
stutter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/build
.PHONY : stutter/fast

#=============================================================================
# Target rules for targets named Catch2

# Build rule for target.
Catch2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2
.PHONY : Catch2

# fast build rule for target.
Catch2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2.dir/build
.PHONY : Catch2/fast

#=============================================================================
# Target rules for targets named Catch2WithMain

# Build rule for target.
Catch2WithMain: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Catch2WithMain
.PHONY : Catch2WithMain

# fast build rule for target.
Catch2WithMain/fast:
	$(MAKE) $(MAKESILENT) -f _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build.make _deps/catch2-build/src/CMakeFiles/Catch2WithMain.dir/build
.PHONY : Catch2WithMain/fast

src/analyzer.o: src/analyzer.cpp.o
.PHONY : src/analyzer.o

# target to build an object file
src/analyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/analyzer.cpp.o
.PHONY : src/analyzer.cpp.o

src/analyzer.i: src/analyzer.cpp.i
.PHONY : src/analyzer.i

# target to preprocess a source file
src/analyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/analyzer.cpp.i
.PHONY : src/analyzer.cpp.i

src/analyzer.s: src/analyzer.cpp.s
.PHONY : src/analyzer.s

# target to generate assembly for a file
src/analyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/analyzer.cpp.s
.PHONY : src/analyzer.cpp.s

src/bytecode.o: src/bytecode.cpp.o
.PHONY : src/bytecode.o

# target to build an object file
src/bytecode.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/bytecode.cpp.o
.PHONY : src/bytecode.cpp.o

src/bytecode.i: src/bytecode.cpp.i
.PHONY : src/bytecode.i

# target to preprocess a source file
src/bytecode.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/bytecode.cpp.i
.PHONY : src/bytecode.cpp.i

src/bytecode.s: src/bytecode.cpp.s
.PHONY : src/bytecode.s

# target to generate assembly for a file
src/bytecode.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/bytecode.cpp.s
.PHONY : src/bytecode.cpp.s

src/error.o: src/error.cpp.o
.PHONY : src/error.o

# target to build an object file
src/error.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/error.cpp.o
.PHONY : src/error.cpp.o

src/error.i: src/error.cpp.i
.PHONY : src/error.i

# target to preprocess a source file
src/error.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/error.cpp.i
.PHONY : src/error.cpp.i

src/error.s: src/error.cpp.s
.PHONY : src/error.s

# target to generate assembly for a file
src/error.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/error.cpp.s
.PHONY : src/error.cpp.s

src/lexer.o: src/lexer.cpp.o
.PHONY : src/lexer.o

# target to build an object file
src/lexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/lexer.cpp.o
.PHONY : src/lexer.cpp.o

src/lexer.i: src/lexer.cpp.i
.PHONY : src/lexer.i

# target to preprocess a source file
src/lexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/lexer.cpp.i
.PHONY : src/lexer.cpp.i

src/lexer.s: src/lexer.cpp.s
.PHONY : src/lexer.s

# target to generate assembly for a file
src/lexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/lexer.cpp.s
.PHONY : src/lexer.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/runtime.o: src/runtime.cpp.o
.PHONY : src/runtime.o

# target to build an object file
src/runtime.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/runtime.cpp.o
.PHONY : src/runtime.cpp.o

src/runtime.i: src/runtime.cpp.i
.PHONY : src/runtime.i

# target to preprocess a source file
src/runtime.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/runtime.cpp.i
.PHONY : src/runtime.cpp.i

src/runtime.s: src/runtime.cpp.s
.PHONY : src/runtime.s

# target to generate assembly for a file
src/runtime.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/runtime.cpp.s
.PHONY : src/runtime.cpp.s

src/stutter.o: src/stutter.cpp.o
.PHONY : src/stutter.o

# target to build an object file
src/stutter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/stutter.cpp.o
.PHONY : src/stutter.cpp.o

src/stutter.i: src/stutter.cpp.i
.PHONY : src/stutter.i

# target to preprocess a source file
src/stutter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/stutter.cpp.i
.PHONY : src/stutter.cpp.i

src/stutter.s: src/stutter.cpp.s
.PHONY : src/stutter.s

# target to generate assembly for a file
src/stutter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/stutter.dir/build.make CMakeFiles/stutter.dir/src/stutter.cpp.s
.PHONY : src/stutter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Catch2"
	@echo "... Catch2WithMain"
	@echo "... stutter"
	@echo "... src/analyzer.o"
	@echo "... src/analyzer.i"
	@echo "... src/analyzer.s"
	@echo "... src/bytecode.o"
	@echo "... src/bytecode.i"
	@echo "... src/bytecode.s"
	@echo "... src/error.o"
	@echo "... src/error.i"
	@echo "... src/error.s"
	@echo "... src/lexer.o"
	@echo "... src/lexer.i"
	@echo "... src/lexer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/runtime.o"
	@echo "... src/runtime.i"
	@echo "... src/runtime.s"
	@echo "... src/stutter.o"
	@echo "... src/stutter.i"
	@echo "... src/stutter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

